
base {
    log_info = on;
    log_debug = off;
    daemon = off;
    user = redsocks;
    group = redsocks;
    redirector = iptables;
}

redsocks {
    local_ip = 127.0.0.1;
    local_port = 1080;
    ip = ${REDSOCKS_TARGET_IP};
    port = ${REDSOCKS_TARGET_PORT};
    type = ${REDSOCKS_TARGET_TYPE};
}
